package com.in.den.android.openweather.db;

import org.greenrobot.greendao.annotation.*;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "WEATHER".
 */
@Entity
public class Weather implements Serializable {

    @Id(autoincrement = true)
    private Long id;
    private long dt;
    private Double temp_day;
    private Double temp_min;
    private Double temp_max;
    private Double temp_night;
    private Double temp_eve;
    private Double temp_morning;
    private Double pressure;
    private Double humidity;
    private Double speed;
    private Double deg;
    private Double cloud;
    private Double rain;
    private Integer weather_id;
    private String weather_main;
    private String weather_description;
    private Integer owcityid;
    private long locationId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 556711069)
    public Weather() {
    }

    public Weather(Long id) {
        this.id = id;
    }

    @Generated(hash = 1357305385)
    public Weather(Long id, long dt, Double temp_day, Double temp_min, Double temp_max, Double temp_night, Double temp_eve, Double temp_morning, Double pressure, Double humidity, Double speed, Double deg, Double cloud, Double rain, Integer weather_id, String weather_main, String weather_description, Integer owcityid, long locationId) {
        this.id = id;
        this.dt = dt;
        this.temp_day = temp_day;
        this.temp_min = temp_min;
        this.temp_max = temp_max;
        this.temp_night = temp_night;
        this.temp_eve = temp_eve;
        this.temp_morning = temp_morning;
        this.pressure = pressure;
        this.humidity = humidity;
        this.speed = speed;
        this.deg = deg;
        this.cloud = cloud;
        this.rain = rain;
        this.weather_id = weather_id;
        this.weather_main = weather_main;
        this.weather_description = weather_description;
        this.owcityid = owcityid;
        this.locationId = locationId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getDt() {
        return dt;
    }

    public void setDt(long dt) {
        this.dt = dt;
    }

    public Double getTemp_day() {
        return temp_day;
    }

    public void setTemp_day(Double temp_day) {
        this.temp_day = temp_day;
    }

    public Double getTemp_min() {
        return temp_min;
    }

    public void setTemp_min(Double temp_min) {
        this.temp_min = temp_min;
    }

    public Double getTemp_max() {
        return temp_max;
    }

    public void setTemp_max(Double temp_max) {
        this.temp_max = temp_max;
    }

    public Double getTemp_night() {
        return temp_night;
    }

    public void setTemp_night(Double temp_night) {
        this.temp_night = temp_night;
    }

    public Double getTemp_eve() {
        return temp_eve;
    }

    public void setTemp_eve(Double temp_eve) {
        this.temp_eve = temp_eve;
    }

    public Double getTemp_morning() {
        return temp_morning;
    }

    public void setTemp_morning(Double temp_morning) {
        this.temp_morning = temp_morning;
    }

    public Double getPressure() {
        return pressure;
    }

    public void setPressure(Double pressure) {
        this.pressure = pressure;
    }

    public Double getHumidity() {
        return humidity;
    }

    public void setHumidity(Double humidity) {
        this.humidity = humidity;
    }

    public Double getSpeed() {
        return speed;
    }

    public void setSpeed(Double speed) {
        this.speed = speed;
    }

    public Double getDeg() {
        return deg;
    }

    public void setDeg(Double deg) {
        this.deg = deg;
    }

    public Double getCloud() {
        return cloud;
    }

    public void setCloud(Double cloud) {
        this.cloud = cloud;
    }

    public Double getRain() {
        return rain;
    }

    public void setRain(Double rain) {
        this.rain = rain;
    }

    public Integer getWeather_id() {
        return weather_id;
    }

    public void setWeather_id(Integer weather_id) {
        this.weather_id = weather_id;
    }

    public String getWeather_main() {
        return weather_main;
    }

    public void setWeather_main(String weather_main) {
        this.weather_main = weather_main;
    }

    public String getWeather_description() {
        return weather_description;
    }

    public void setWeather_description(String weather_description) {
        this.weather_description = weather_description;
    }

    public Integer getOwcityid() {
        return owcityid;
    }

    public void setOwcityid(Integer owcityid) {
        this.owcityid = owcityid;
    }

    public long getLocationId() {
        return locationId;
    }

    public void setLocationId(long locationId) {
        this.locationId = locationId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
